### ISSUE TITLE
Enable Dependabot for this project

### ISSUE THREAD

**Issue by ferrarimarco** [dcassioli/cassios-website#7]
After (and if) #1 and #2 are merged, this project could benefit from [Dependabot](https://dependabot.com/).

This (free) service is able to watch dependency descriptors for a variety of languages and tools (Docker, npm, bundler...).

When it spots an outdated dependency, it automatically creates a PR to update such dependency. Example: https://github.com/ferrarimarco/personal-website/pull/45

For this project it could watch:
1. `Dockerfile`
1. `Gemfile`
1. `package.json`

NOTE: rembember to delete (and add to `.gitignore`) `Gemfile.lock` and `package-lock.json` if enabling this service.

**Comment by dcassioli** [comment]
Dependabot has been enabled, dependencies are being checked on a daily basis.
